# Curated Malaysian and Southeast Asian recipe corpus.
# Phase 1: ~15 seed recipes.  Instructions are never stored here — we only
# hold enough metadata to compute ingredient match % and link to the source.

RECIPES = [
    {
        "id": "char-kway-teow",
        "name": "Char Kway Teow",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/char-kway-teow/",
        "cuisine": "Malaysian",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "ingredients": [
            "flat rice noodles",
            "prawns",
            "bean sprouts",
            "chives",
            "eggs",
            "lap cheong",
            "dark soy sauce",
            "light soy sauce",
            "fish sauce",
            "oil",
            "garlic",
        ],
    },
    {
        "id": "nasi-lemak",
        "name": "Nasi Lemak",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/nasi-lemak/",
        "cuisine": "Malaysian",
        "cook_time": "45 min",
        "difficulty": "Medium",
        "ingredients": [
            "rice",
            "coconut milk",
            "pandan leaves",
            "anchovies",
            "peanuts",
            "cucumber",
            "eggs",
            "sambal",
            "shallots",
            "dried chillies",
            "belacan",
            "tamarind",
        ],
    },
    {
        "id": "laksa-lemak",
        "name": "Laksa Lemak",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/laksa/",
        "cuisine": "Malaysian",
        "cook_time": "60 min",
        "difficulty": "Hard",
        "ingredients": [
            "rice noodles",
            "coconut milk",
            "prawns",
            "fish cake",
            "bean sprouts",
            "laksa paste",
            "lemongrass",
            "galangal",
            "dried chillies",
            "belacan",
            "shallots",
            "oil",
        ],
    },
    {
        "id": "beef-rendang",
        "name": "Beef Rendang",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/beef-rendang/",
        "cuisine": "Malaysian",
        "cook_time": "90 min",
        "difficulty": "Hard",
        "ingredients": [
            "beef",
            "coconut milk",
            "lemongrass",
            "galangal",
            "turmeric",
            "dried chillies",
            "shallots",
            "garlic",
            "ginger",
            "kaffir lime leaves",
            "toasted coconut",
            "oil",
        ],
    },
    {
        "id": "mee-goreng",
        "name": "Mee Goreng",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/mee-goreng/",
        "cuisine": "Malaysian",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "yellow noodles",
            "prawns",
            "bean sprouts",
            "eggs",
            "tomatoes",
            "tofu",
            "garlic",
            "chilli paste",
            "soy sauce",
            "oyster sauce",
            "oil",
        ],
    },
    {
        "id": "hainanese-chicken-rice",
        "name": "Hainanese Chicken Rice",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/hainanese-chicken-rice/",
        "cuisine": "Singaporean",
        "cook_time": "60 min",
        "difficulty": "Medium",
        "ingredients": [
            "whole chicken",
            "rice",
            "ginger",
            "garlic",
            "sesame oil",
            "light soy sauce",
            "spring onions",
            "chilli sauce",
            "dark soy sauce",
        ],
    },
    {
        "id": "pad-thai",
        "name": "Pad Thai",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/pad-thai/",
        "cuisine": "Thai",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "ingredients": [
            "rice noodles",
            "prawns",
            "eggs",
            "bean sprouts",
            "tofu",
            "fish sauce",
            "tamarind",
            "palm sugar",
            "chilli flakes",
            "peanuts",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "tom-yum-soup",
        "name": "Tom Yum Soup",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/tom-yum-soup/",
        "cuisine": "Thai",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "prawns",
            "lemongrass",
            "galangal",
            "kaffir lime leaves",
            "mushrooms",
            "chillies",
            "fish sauce",
            "lime juice",
            "coconut milk",
        ],
    },
    {
        "id": "stir-fried-bok-choy",
        "name": "Stir-Fried Bok Choy with Garlic",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/stir-fried-bok-choy/",
        "cuisine": "Chinese",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "ingredients": [
            "bok choy",
            "garlic",
            "oyster sauce",
            "sesame oil",
            "light soy sauce",
            "oil",
        ],
    },
    {
        "id": "steamed-fish-soy",
        "name": "Steamed Fish with Soy",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/steamed-fish/",
        "cuisine": "Chinese",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "fish",
            "light soy sauce",
            "dark soy sauce",
            "sesame oil",
            "ginger",
            "spring onions",
            "oil",
        ],
    },
    {
        "id": "mapo-tofu",
        "name": "Mapo Tofu",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/ma-po-tofu/",
        "cuisine": "Chinese",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "ingredients": [
            "tofu",
            "minced pork",
            "doubanjiang",
            "garlic",
            "ginger",
            "spring onions",
            "soy sauce",
            "sesame oil",
            "oil",
            "sichuan peppercorns",
        ],
    },
    {
        "id": "adobo",
        "name": "Chicken Adobo",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/chicken-adobo/",
        "cuisine": "Filipino",
        "cook_time": "45 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "soy sauce",
            "vinegar",
            "garlic",
            "bay leaves",
            "black peppercorns",
            "oil",
        ],
    },
    {
        "id": "sambal-goreng",
        "name": "Sambal Goreng Tempeh",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/sambal-goreng-tempeh/",
        "cuisine": "Indonesian",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "tempeh",
            "dried chillies",
            "shallots",
            "garlic",
            "belacan",
            "tamarind",
            "palm sugar",
            "oil",
        ],
    },
    {
        "id": "congee",
        "name": "Cantonese Congee",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/congee/",
        "cuisine": "Chinese",
        "cook_time": "60 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice",
            "chicken stock",
            "ginger",
            "spring onions",
            "sesame oil",
            "light soy sauce",
            "white pepper",
        ],
    },
    {
        "id": "kung-pao-chicken",
        "name": "Kung Pao Chicken",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/kung-pao-chicken/",
        "cuisine": "Chinese",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "peanuts",
            "dried chillies",
            "sichuan peppercorns",
            "garlic",
            "ginger",
            "soy sauce",
            "dark soy sauce",
            "black vinegar",
            "sesame oil",
            "oil",
        ],
    },
]
