# Curated Malaysian and Southeast Asian recipe corpus.
# Instructions are never stored here — we only hold enough metadata to compute
# ingredient match % and link to the source.

RECIPES = [
    # ── Malaysian ─────────────────────────────────────────────────────────────
    {
        "id": "char-kway-teow",
        "name": "Char Kway Teow",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/char-kway-teow/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "15 min",
        "difficulty": "Medium",
        "ingredients": [
            "flat rice noodles",
            "prawns",
            "bean sprouts",
            "chives",
            "eggs",
            "lap cheong",
            "dark soy sauce",
            "light soy sauce",
            "fish sauce",
            "oil",
            "garlic",
        ],
    },
    {
        "id": "nasi-lemak",
        "name": "Nasi Lemak",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/nasi-lemak/",
        "cuisine": "Malaysian",
        "cook_time": "45 min",
        "difficulty": "Medium",
        "ingredients": [
            "rice",
            "coconut milk",
            "pandan leaves",
            "anchovies",
            "peanuts",
            "cucumber",
            "eggs",
            "sambal",
            "shallots",
            "dried chillies",
            "belacan",
            "tamarind",
        ],
    },
    {
        "id": "laksa-lemak",
        "name": "Laksa Lemak",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/laksa/",
        "cuisine": "Malaysian",
        "cook_time": "60 min",
        "difficulty": "Hard",
        "ingredients": [
            "rice noodles",
            "coconut milk",
            "prawns",
            "fish cake",
            "bean sprouts",
            "laksa paste",
            "lemongrass",
            "galangal",
            "dried chillies",
            "belacan",
            "shallots",
            "oil",
        ],
    },
    {
        "id": "beef-rendang",
        "name": "Beef Rendang",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/beef-rendang/",
        "cuisine": "Malaysian",
        "cook_time": "90 min",
        "difficulty": "Hard",
        "ingredients": [
            "beef",
            "coconut milk",
            "lemongrass",
            "galangal",
            "turmeric",
            "dried chillies",
            "shallots",
            "garlic",
            "ginger",
            "kaffir lime leaves",
            "toasted coconut",
            "oil",
        ],
    },
    {
        "id": "mee-goreng",
        "name": "Mee Goreng",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/mee-goreng/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "yellow noodles",
            "prawns",
            "bean sprouts",
            "eggs",
            "tomatoes",
            "tofu",
            "garlic",
            "chilli paste",
            "soy sauce",
            "oyster sauce",
            "oil",
        ],
    },
    {
        "id": "hainanese-chicken-rice",
        "name": "Hainanese Chicken Rice",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/hainanese-chicken-rice/recipe/",
        "cuisine": "Singaporean",
        "cook_time": "60 min",
        "difficulty": "Medium",
        "ingredients": [
            "whole chicken",
            "rice",
            "ginger",
            "garlic",
            "sesame oil",
            "light soy sauce",
            "spring onions",
            "chilli sauce",
            "dark soy sauce",
        ],
    },
    {
        "id": "curry-chicken",
        "name": "Malaysian Curry Chicken",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/curry-chicken/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "40 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "coconut milk",
            "curry paste",
            "lemongrass",
            "shallots",
            "garlic",
            "ginger",
            "potatoes",
            "oil",
        ],
    },
    {
        "id": "bak-kut-teh",
        "name": "Bak Kut Teh",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/bak-kut-teh/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "90 min",
        "difficulty": "Medium",
        "ingredients": [
            "pork ribs",
            "garlic",
            "white pepper",
            "soy sauce",
            "dark soy sauce",
            "star anise",
            "cinnamon",
            "oyster sauce",
        ],
    },
    {
        "id": "prawn-mee",
        "name": "Prawn Mee",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/prawn-mee/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "60 min",
        "difficulty": "Hard",
        "ingredients": [
            "prawns",
            "pork ribs",
            "yellow noodles",
            "rice noodles",
            "bean sprouts",
            "kangkung",
            "sambal",
            "shallots",
            "oil",
        ],
    },
    {
        "id": "asam-pedas",
        "name": "Asam Pedas Fish",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/asam-pedas/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "fish",
            "tamarind",
            "tomatoes",
            "dried chillies",
            "lemongrass",
            "shallots",
            "galangal",
            "belacan",
            "oil",
        ],
    },
    {
        "id": "claypot-chicken",
        "name": "Claypot Chicken Rice",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/claypot-chicken-rice/",
        "cuisine": "Malaysian",
        "cook_time": "45 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "rice",
            "lap cheong",
            "ginger",
            "dark soy sauce",
            "sesame oil",
            "oyster sauce",
            "dried mushrooms",
            "spring onions",
        ],
    },
    {
        "id": "pan-mee",
        "name": "Pan Mee",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/pan-mee/",
        "cuisine": "Malaysian",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "flour",
            "minced pork",
            "anchovies",
            "dried shrimp",
            "eggs",
            "mushrooms",
            "dark soy sauce",
            "soy sauce",
            "oil",
        ],
    },
    {
        "id": "satay-chicken",
        "name": "Chicken Satay",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/chicken-satay/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "lemongrass",
            "turmeric",
            "shallots",
            "garlic",
            "peanuts",
            "palm sugar",
            "tamarind",
            "oil",
        ],
    },
    {
        "id": "masak-lemak",
        "name": "Masak Lemak Cili Api",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/masak-lemak/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "35 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "coconut milk",
            "turmeric",
            "lemongrass",
            "bird's eye chillies",
            "shallots",
            "galangal",
        ],
    },
    {
        "id": "ikan-bakar",
        "name": "Ikan Bakar",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/ikan-bakar/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "ingredients": [
            "fish",
            "belacan",
            "turmeric",
            "lemongrass",
            "lime juice",
            "shallots",
            "garlic",
            "chillies",
        ],
    },
    {
        "id": "mee-rebus",
        "name": "Mee Rebus",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/mee-rebus/",
        "cuisine": "Malaysian",
        "cook_time": "45 min",
        "difficulty": "Medium",
        "ingredients": [
            "yellow noodles",
            "prawns",
            "eggs",
            "potatoes",
            "dried shrimp",
            "shallots",
            "garlic",
            "soy sauce",
            "oil",
        ],
    },
    {
        "id": "char-siu",
        "name": "Char Siu Pork",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/char-siu/",
        "cuisine": "Malaysian",
        "cook_time": "40 min",
        "difficulty": "Easy",
        "ingredients": [
            "pork",
            "hoisin sauce",
            "soy sauce",
            "honey",
            "five spice",
            "dark soy sauce",
            "garlic",
            "sesame oil",
        ],
    },
    {
        "id": "wonton-soup",
        "name": "Wonton Soup",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/wonton-soup/",
        "cuisine": "Malaysian",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "pork",
            "prawns",
            "wonton wrappers",
            "spring onions",
            "sesame oil",
            "chicken stock",
            "ginger",
            "soy sauce",
        ],
    },
    {
        "id": "yong-tau-fu",
        "name": "Yong Tau Fu",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/yong-tau-fu/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "45 min",
        "difficulty": "Hard",
        "ingredients": [
            "tofu",
            "fish paste",
            "vegetables",
            "oyster sauce",
            "sesame oil",
            "garlic",
            "spring onions",
        ],
    },
    {
        "id": "hokkien-mee",
        "name": "Hokkien Mee",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/hokkien-mee/",
        "cuisine": "Malaysian",
        "cook_time": "20 min",
        "difficulty": "Medium",
        "ingredients": [
            "yellow noodles",
            "pork",
            "prawns",
            "squid",
            "eggs",
            "dark soy sauce",
            "garlic",
            "spring onions",
            "lard",
            "oil",
        ],
    },
    # ── Thai ──────────────────────────────────────────────────────────────────
    {
        "id": "pad-thai",
        "name": "Pad Thai",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/pad-thai/",
        "cuisine": "Thai",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "ingredients": [
            "rice noodles",
            "prawns",
            "eggs",
            "bean sprouts",
            "tofu",
            "fish sauce",
            "tamarind",
            "palm sugar",
            "chilli flakes",
            "peanuts",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "tom-yum-soup",
        "name": "Tom Yum Soup",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/tom-yum-soup/recipe/",
        "cuisine": "Thai",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "prawns",
            "lemongrass",
            "galangal",
            "kaffir lime leaves",
            "mushrooms",
            "chillies",
            "fish sauce",
            "lime juice",
            "coconut milk",
        ],
    },
    {
        "id": "green-curry",
        "name": "Thai Green Curry",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/green-curry-chicken/",
        "cuisine": "Thai",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "coconut milk",
            "green curry paste",
            "kaffir lime leaves",
            "fish sauce",
            "palm sugar",
            "bamboo shoots",
            "thai basil",
            "oil",
        ],
    },
    {
        "id": "red-curry",
        "name": "Thai Red Curry",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/thai-red-curry/",
        "cuisine": "Thai",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "coconut milk",
            "red curry paste",
            "bamboo shoots",
            "kaffir lime leaves",
            "fish sauce",
            "palm sugar",
            "thai basil",
            "oil",
        ],
    },
    {
        "id": "massaman-curry",
        "name": "Massaman Curry",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/massaman-curry/recipe/",
        "cuisine": "Thai",
        "cook_time": "60 min",
        "difficulty": "Medium",
        "ingredients": [
            "beef",
            "coconut milk",
            "massaman paste",
            "potatoes",
            "peanuts",
            "palm sugar",
            "fish sauce",
            "tamarind",
            "cinnamon",
            "star anise",
        ],
    },
    {
        "id": "som-tam",
        "name": "Som Tam",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/thai-green-papaya-salad/",
        "cuisine": "Thai",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "green papaya",
            "tomatoes",
            "fish sauce",
            "lime juice",
            "palm sugar",
            "dried shrimp",
            "chillies",
            "peanuts",
            "garlic",
        ],
    },
    {
        "id": "pad-see-ew",
        "name": "Pad See Ew",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/pad-see-ew/",
        "cuisine": "Thai",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "flat rice noodles",
            "chinese broccoli",
            "eggs",
            "chicken",
            "fish sauce",
            "dark soy sauce",
            "oyster sauce",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "pad-krapow",
        "name": "Thai Basil Chicken",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/thai-basil-chicken/",
        "cuisine": "Thai",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "thai basil",
            "fish sauce",
            "oyster sauce",
            "garlic",
            "chillies",
            "eggs",
            "oil",
        ],
    },
    {
        "id": "tom-kha-gai",
        "name": "Tom Kha Gai",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/tom-kha-gai/",
        "cuisine": "Thai",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "coconut milk",
            "galangal",
            "lemongrass",
            "kaffir lime leaves",
            "mushrooms",
            "fish sauce",
            "lime juice",
            "chillies",
        ],
    },
    {
        "id": "khao-pad",
        "name": "Thai Fried Rice",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/thai-fried-rice/",
        "cuisine": "Thai",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice",
            "eggs",
            "fish sauce",
            "soy sauce",
            "spring onions",
            "cucumber",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "larb-gai",
        "name": "Larb Gai",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/chicken-larb/",
        "cuisine": "Thai",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "minced chicken",
            "fish sauce",
            "lime juice",
            "shallots",
            "chillies",
            "mint",
            "spring onions",
            "toasted rice",
        ],
    },
    {
        "id": "mango-sticky-rice",
        "name": "Mango Sticky Rice",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/mango-sticky-rice/",
        "cuisine": "Thai",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "glutinous rice",
            "coconut milk",
            "mango",
            "palm sugar",
            "pandan leaves",
            "sesame seeds",
        ],
    },
    {
        "id": "khao-tom",
        "name": "Thai Rice Soup",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/chicken-pho/",
        "cuisine": "Thai",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice",
            "pork",
            "ginger",
            "garlic",
            "fish sauce",
            "spring onions",
            "sesame oil",
            "white pepper",
        ],
    },
    # ── Filipino ──────────────────────────────────────────────────────────────
    {
        "id": "adobo",
        "name": "Chicken Adobo",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/chicken-adobo/",
        "cuisine": "Filipino",
        "cook_time": "45 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "soy sauce",
            "vinegar",
            "garlic",
            "bay leaves",
            "black peppercorns",
            "oil",
        ],
    },
    {
        "id": "pork-adobo",
        "name": "Pork Adobo",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/pork-adobo/",
        "cuisine": "Filipino",
        "cook_time": "50 min",
        "difficulty": "Easy",
        "ingredients": [
            "pork",
            "soy sauce",
            "vinegar",
            "garlic",
            "bay leaves",
            "black peppercorns",
            "palm sugar",
            "oil",
        ],
    },
    {
        "id": "sinigang",
        "name": "Sinigang",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/sinigang/",
        "cuisine": "Filipino",
        "cook_time": "45 min",
        "difficulty": "Easy",
        "ingredients": [
            "pork",
            "tamarind",
            "tomatoes",
            "kangkung",
            "aubergine",
            "radish",
            "fish sauce",
            "onions",
        ],
    },
    {
        "id": "kare-kare",
        "name": "Kare-Kare",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/kare-kare/",
        "cuisine": "Filipino",
        "cook_time": "90 min",
        "difficulty": "Hard",
        "ingredients": [
            "oxtail",
            "peanuts",
            "banana blossom",
            "aubergine",
            "bean sprouts",
            "shrimp paste",
            "garlic",
            "onions",
            "annatto",
        ],
    },
    {
        "id": "arroz-caldo",
        "name": "Arroz Caldo",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/arroz-caldo/",
        "cuisine": "Filipino",
        "cook_time": "45 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "rice",
            "ginger",
            "garlic",
            "fish sauce",
            "spring onions",
            "eggs",
            "oil",
        ],
    },
    {
        "id": "pancit-canton",
        "name": "Pancit Canton",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/pancit-canton/",
        "cuisine": "Filipino",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "egg noodles",
            "pork",
            "prawns",
            "vegetables",
            "soy sauce",
            "chicken stock",
            "garlic",
            "onions",
            "spring onions",
        ],
    },
    {
        "id": "bicol-express",
        "name": "Bicol Express",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/bicol-express/",
        "cuisine": "Filipino",
        "cook_time": "40 min",
        "difficulty": "Easy",
        "ingredients": [
            "pork",
            "coconut milk",
            "chillies",
            "shrimp paste",
            "garlic",
            "onions",
            "oil",
        ],
    },
    {
        "id": "chicken-tinola",
        "name": "Chicken Tinola",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/chicken-tinola/",
        "cuisine": "Filipino",
        "cook_time": "35 min",
        "difficulty": "Easy",
        "ingredients": [
            "chicken",
            "ginger",
            "papaya",
            "chilli leaves",
            "fish sauce",
            "garlic",
            "onions",
            "oil",
        ],
    },
    {
        "id": "giniling",
        "name": "Giniling",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/ground-pork-giniling-recipe/",
        "cuisine": "Filipino",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "minced pork",
            "potatoes",
            "tomatoes",
            "soy sauce",
            "fish sauce",
            "raisins",
            "garlic",
            "onions",
            "oil",
        ],
    },
    {
        "id": "lechon-kawali",
        "name": "Lechon Kawali",
        "source": "Panlasang Pinoy",
        "source_url": "https://panlasangpinoy.com/lechon-kawali/",
        "cuisine": "Filipino",
        "cook_time": "60 min",
        "difficulty": "Medium",
        "ingredients": [
            "pork belly",
            "garlic",
            "bay leaves",
            "black peppercorns",
            "soy sauce",
            "oil",
        ],
    },
    # ── Indonesian ────────────────────────────────────────────────────────────
    {
        "id": "sambal-goreng",
        "name": "Sambal Goreng Tempeh",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/sambal-goreng-tempeh/recipe/",
        "cuisine": "Indonesian",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "tempeh",
            "dried chillies",
            "shallots",
            "garlic",
            "belacan",
            "tamarind",
            "palm sugar",
            "oil",
        ],
    },
    {
        "id": "nasi-goreng",
        "name": "Nasi Goreng",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/nasi-goreng/",
        "cuisine": "Indonesian",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice",
            "eggs",
            "shrimp paste",
            "sweet soy sauce",
            "shallots",
            "garlic",
            "chillies",
            "prawns",
            "oil",
        ],
    },
    {
        "id": "mie-goreng-indonesia",
        "name": "Mie Goreng",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/mie-goreng/",
        "cuisine": "Indonesian",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "egg noodles",
            "eggs",
            "cabbage",
            "carrots",
            "sweet soy sauce",
            "chilli",
            "garlic",
            "shallots",
            "oil",
        ],
    },
    {
        "id": "soto-ayam",
        "name": "Soto Ayam",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/soto-ayam/",
        "cuisine": "Indonesian",
        "cook_time": "60 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "lemongrass",
            "turmeric",
            "galangal",
            "bean sprouts",
            "vermicelli",
            "hard-boiled eggs",
            "shallots",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "opor-ayam",
        "name": "Opor Ayam",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/opor-ayam/recipe/",
        "cuisine": "Indonesian",
        "cook_time": "50 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "coconut milk",
            "lemongrass",
            "galangal",
            "candlenut",
            "white pepper",
            "shallots",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "gado-gado",
        "name": "Gado-Gado",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/gado-gado/",
        "cuisine": "Indonesian",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "peanuts",
            "tofu",
            "eggs",
            "bean sprouts",
            "tempeh",
            "coconut milk",
            "tamarind",
            "palm sugar",
            "chillies",
            "garlic",
        ],
    },
    {
        "id": "sate-ayam",
        "name": "Sate Ayam",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/chicken-satay/recipe/",
        "cuisine": "Indonesian",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "sweet soy sauce",
            "peanuts",
            "lemongrass",
            "garlic",
            "shallots",
            "turmeric",
            "oil",
        ],
    },
    {
        "id": "sayur-lodeh",
        "name": "Sayur Lodeh",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/sayur-lodeh/recipe/",
        "cuisine": "Indonesian",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "coconut milk",
            "tofu",
            "tempeh",
            "lemongrass",
            "galangal",
            "vegetables",
            "shallots",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "tumis-kangkung",
        "name": "Tumis Kangkung",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/kangkung-belacan/recipe/",
        "cuisine": "Indonesian",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "ingredients": [
            "kangkung",
            "garlic",
            "chillies",
            "belacan",
            "oyster sauce",
            "oil",
        ],
    },
    # ── Vietnamese ────────────────────────────────────────────────────────────
    {
        "id": "pho-bo",
        "name": "Pho Bo",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/pho-vietnamese-noodle-soup/",
        "cuisine": "Vietnamese",
        "cook_time": "180 min",
        "difficulty": "Hard",
        "ingredients": [
            "beef brisket",
            "rice noodles",
            "star anise",
            "cinnamon",
            "ginger",
            "onions",
            "fish sauce",
            "bean sprouts",
            "spring onions",
            "lime juice",
        ],
    },
    {
        "id": "pho-ga",
        "name": "Pho Ga",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/chicken-pho/",
        "cuisine": "Vietnamese",
        "cook_time": "90 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "rice noodles",
            "ginger",
            "star anise",
            "fish sauce",
            "bean sprouts",
            "spring onions",
            "lime juice",
        ],
    },
    {
        "id": "bun-bo-hue",
        "name": "Bun Bo Hue",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/green-curry-chicken/",
        "cuisine": "Vietnamese",
        "cook_time": "120 min",
        "difficulty": "Hard",
        "ingredients": [
            "pork",
            "beef",
            "lemongrass",
            "shrimp paste",
            "rice vermicelli",
            "banana blossom",
            "chillies",
            "fish sauce",
            "spring onions",
        ],
    },
    {
        "id": "banh-xeo",
        "name": "Banh Xeo",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/thai-green-papaya-salad/",
        "cuisine": "Vietnamese",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "rice flour",
            "turmeric",
            "coconut milk",
            "prawns",
            "pork",
            "bean sprouts",
            "spring onions",
            "fish sauce",
            "oil",
        ],
    },
    {
        "id": "canh-chua",
        "name": "Canh Chua",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/chicken-larb/",
        "cuisine": "Vietnamese",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "fish",
            "tamarind",
            "tomatoes",
            "pineapple",
            "bean sprouts",
            "spring onions",
            "fish sauce",
        ],
    },
    {
        "id": "bo-kho",
        "name": "Bo Kho",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/bo-kho/",
        "cuisine": "Vietnamese",
        "cook_time": "90 min",
        "difficulty": "Medium",
        "ingredients": [
            "beef",
            "lemongrass",
            "star anise",
            "carrots",
            "tomatoes",
            "fish sauce",
            "garlic",
            "ginger",
            "oil",
        ],
    },
    {
        "id": "goi-cuon",
        "name": "Goi Cuon",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/chicken-pho/",
        "cuisine": "Vietnamese",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice paper",
            "prawns",
            "pork",
            "rice vermicelli",
            "lettuce",
            "mint",
            "hoisin sauce",
            "peanuts",
        ],
    },
    {
        "id": "ca-kho-to",
        "name": "Ca Kho To",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/pho-vietnamese-noodle-soup/",
        "cuisine": "Vietnamese",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "fish",
            "fish sauce",
            "ginger",
            "shallots",
            "chillies",
            "palm sugar",
            "oil",
        ],
    },
    {
        "id": "bun-cha",
        "name": "Bun Cha",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/chicken-pho/",
        "cuisine": "Vietnamese",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "pork",
            "fish sauce",
            "garlic",
            "shallots",
            "rice vermicelli",
            "mint",
            "lettuce",
            "lime juice",
        ],
    },
    # ── Singaporean ───────────────────────────────────────────────────────────
    {
        "id": "chilli-crab",
        "name": "Chilli Crab",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/chilli-crab/recipe/",
        "cuisine": "Singaporean",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "crab",
            "tomato sauce",
            "chilli paste",
            "eggs",
            "garlic",
            "ginger",
            "spring onions",
            "oil",
        ],
    },
    {
        "id": "bak-chor-mee",
        "name": "Bak Chor Mee",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/bak-chor-mee/recipe/",
        "cuisine": "Singaporean",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "minced pork",
            "noodles",
            "pork liver",
            "fish cake",
            "vinegar",
            "dark soy sauce",
            "sesame oil",
            "spring onions",
        ],
    },
    {
        "id": "prawn-noodle",
        "name": "Prawn Noodle Soup",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/prawn-noodle-soup/recipe/",
        "cuisine": "Singaporean",
        "cook_time": "60 min",
        "difficulty": "Hard",
        "ingredients": [
            "prawns",
            "pork ribs",
            "yellow noodles",
            "bean sprouts",
            "kangkung",
            "sambal",
            "sesame oil",
            "shallots",
        ],
    },
    {
        "id": "singapore-fried-noodles",
        "name": "Singapore Noodles",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/singapore-noodles/",
        "cuisine": "Singaporean",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice vermicelli",
            "curry powder",
            "prawns",
            "eggs",
            "bean sprouts",
            "garlic",
            "spring onions",
            "oil",
        ],
    },
    {
        "id": "oyster-omelette",
        "name": "Oyster Omelette",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/oyster-omelette/recipe/",
        "cuisine": "Singaporean",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "oysters",
            "eggs",
            "tapioca starch",
            "fish sauce",
            "chilli sauce",
            "spring onions",
            "oil",
        ],
    },
    # ── Chinese ───────────────────────────────────────────────────────────────
    {
        "id": "stir-fried-bok-choy",
        "name": "Stir-Fried Bok Choy with Garlic",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/stir-fried-bok-choy/",
        "cuisine": "Chinese",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "ingredients": [
            "bok choy",
            "garlic",
            "oyster sauce",
            "sesame oil",
            "light soy sauce",
            "oil",
        ],
    },
    {
        "id": "steamed-fish-soy",
        "name": "Steamed Fish with Soy",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/steamed-fish/",
        "cuisine": "Chinese",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "fish",
            "light soy sauce",
            "dark soy sauce",
            "sesame oil",
            "ginger",
            "spring onions",
            "oil",
        ],
    },
    {
        "id": "mapo-tofu",
        "name": "Mapo Tofu",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/ma-po-tofu/",
        "cuisine": "Chinese",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "ingredients": [
            "tofu",
            "minced pork",
            "doubanjiang",
            "garlic",
            "ginger",
            "spring onions",
            "soy sauce",
            "sesame oil",
            "oil",
            "sichuan peppercorns",
        ],
    },
    {
        "id": "congee",
        "name": "Cantonese Congee",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/20-minute-congee-recipe/",
        "cuisine": "Chinese",
        "cook_time": "60 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice",
            "chicken stock",
            "ginger",
            "spring onions",
            "sesame oil",
            "light soy sauce",
            "white pepper",
        ],
    },
    {
        "id": "kung-pao-chicken",
        "name": "Kung Pao Chicken",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/kung-pao-chicken/",
        "cuisine": "Chinese",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "peanuts",
            "dried chillies",
            "sichuan peppercorns",
            "garlic",
            "ginger",
            "soy sauce",
            "dark soy sauce",
            "black vinegar",
            "sesame oil",
            "oil",
        ],
    },
    {
        "id": "sweet-sour-pork",
        "name": "Sweet and Sour Pork",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/sweet-and-sour-pork/",
        "cuisine": "Chinese",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "pork",
            "pineapple",
            "tomatoes",
            "vinegar",
            "palm sugar",
            "garlic",
            "ginger",
            "soy sauce",
            "oil",
        ],
    },
    {
        "id": "braised-pork-belly",
        "name": "Hong Shao Rou",
        "source": "The Woks of Life",
        "source_url": "https://iamafoodblog.com/bun-bo-hue-recipe-the-spicy-vietnamese-noodle-soup-you-never-knew-you-loved/",
        "cuisine": "Chinese",
        "cook_time": "90 min",
        "difficulty": "Medium",
        "ingredients": [
            "pork belly",
            "soy sauce",
            "dark soy sauce",
            "rock sugar",
            "ginger",
            "star anise",
            "spring onions",
            "oil",
        ],
    },
    {
        "id": "steamed-pork-ribs",
        "name": "Steamed Pork Ribs with Black Bean",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/steamed-pork-ribs/",
        "cuisine": "Chinese",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "pork ribs",
            "fermented black beans",
            "garlic",
            "oyster sauce",
            "sesame oil",
            "ginger",
            "spring onions",
        ],
    },
    {
        "id": "soy-sauce-chicken",
        "name": "Soy Sauce Chicken",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/soy-sauce-chicken/",
        "cuisine": "Chinese",
        "cook_time": "45 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "dark soy sauce",
            "soy sauce",
            "rock sugar",
            "garlic",
            "ginger",
            "star anise",
            "sesame oil",
        ],
    },
    {
        "id": "braised-tofu",
        "name": "Braised Tofu",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/braised-tofu/",
        "cuisine": "Chinese",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "tofu",
            "oyster sauce",
            "dark soy sauce",
            "garlic",
            "spring onions",
            "sesame oil",
            "oil",
        ],
    },
    {
        "id": "egg-drop-soup",
        "name": "Egg Drop Soup",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/egg-drop-soup/",
        "cuisine": "Chinese",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "eggs",
            "chicken stock",
            "spring onions",
            "sesame oil",
            "white pepper",
            "cornstarch",
        ],
    },
    {
        "id": "hot-sour-soup",
        "name": "Hot and Sour Soup",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/hot-sour-soup/",
        "cuisine": "Chinese",
        "cook_time": "25 min",
        "difficulty": "Easy",
        "ingredients": [
            "pork",
            "tofu",
            "bamboo shoots",
            "mushrooms",
            "black vinegar",
            "white pepper",
            "eggs",
            "soy sauce",
            "sesame oil",
        ],
    },
    {
        "id": "wonton-noodle",
        "name": "Wonton Noodle Soup",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/cantonese-wonton-noodle-soup/",
        "cuisine": "Chinese",
        "cook_time": "40 min",
        "difficulty": "Medium",
        "ingredients": [
            "pork",
            "prawns",
            "wonton wrappers",
            "egg noodles",
            "chicken stock",
            "chinese broccoli",
            "spring onions",
            "sesame oil",
        ],
    },
    {
        "id": "dan-dan-noodles",
        "name": "Dan Dan Noodles",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/dan-dan-noodles/",
        "cuisine": "Chinese",
        "cook_time": "25 min",
        "difficulty": "Medium",
        "ingredients": [
            "noodles",
            "minced pork",
            "sesame paste",
            "chilli oil",
            "sichuan peppercorns",
            "vinegar",
            "garlic",
            "spring onions",
            "soy sauce",
        ],
    },
    {
        "id": "beef-oyster-sauce",
        "name": "Beef with Oyster Sauce",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/beef-oyster-sauce/",
        "cuisine": "Chinese",
        "cook_time": "15 min",
        "difficulty": "Easy",
        "ingredients": [
            "beef",
            "oyster sauce",
            "garlic",
            "ginger",
            "spring onions",
            "sesame oil",
            "soy sauce",
            "oil",
        ],
    },
    {
        "id": "chinese-broccoli-oyster",
        "name": "Chinese Broccoli with Oyster Sauce",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/chinese-broccoli/",
        "cuisine": "Chinese",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "ingredients": [
            "chinese broccoli",
            "oyster sauce",
            "sesame oil",
            "garlic",
            "oil",
        ],
    },
    {
        "id": "stir-fried-eggs-tomatoes",
        "name": "Stir-Fried Eggs with Tomatoes",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/stir-fried-tomato-and-egg/",
        "cuisine": "Chinese",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "ingredients": [
            "eggs",
            "tomatoes",
            "garlic",
            "spring onions",
            "sesame oil",
            "soy sauce",
            "oil",
        ],
    },
    {
        "id": "century-egg-tofu",
        "name": "Century Egg with Tofu",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/spicy-cold-tofu-liangban-dofu/",
        "cuisine": "Chinese",
        "cook_time": "10 min",
        "difficulty": "Easy",
        "ingredients": [
            "century egg",
            "soft tofu",
            "sesame oil",
            "soy sauce",
            "spring onions",
            "garlic",
            "chillies",
        ],
    },
    {
        "id": "pork-rib-soup",
        "name": "Lotus Root Pork Rib Soup",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/lotus-root-pork-soup/",
        "cuisine": "Chinese",
        "cook_time": "90 min",
        "difficulty": "Easy",
        "ingredients": [
            "pork ribs",
            "lotus root",
            "dried mushrooms",
            "ginger",
            "spring onions",
            "white pepper",
        ],
    },
    # ── More Malaysian ────────────────────────────────────────────────────────
    {
        "id": "curry-laksa",
        "name": "Curry Laksa",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/curry-laksa/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "45 min",
        "difficulty": "Medium",
        "ingredients": [
            "coconut milk",
            "laksa paste",
            "rice noodles",
            "prawns",
            "tofu",
            "bean sprouts",
            "fish cake",
            "lemongrass",
            "shallots",
            "oil",
        ],
    },
    {
        "id": "chee-cheong-fun",
        "name": "Chee Cheong Fun",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/chee-cheong-fun/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "rice noodle rolls",
            "sweet soy sauce",
            "sesame oil",
            "sesame seeds",
            "spring onions",
            "sambal",
        ],
    },
    {
        "id": "asam-laksa",
        "name": "Asam Laksa",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/asam-laksa/recipe/",
        "cuisine": "Malaysian",
        "cook_time": "60 min",
        "difficulty": "Hard",
        "ingredients": [
            "mackerel",
            "tamarind",
            "rice noodles",
            "lemongrass",
            "galangal",
            "belacan",
            "dried chillies",
            "cucumber",
            "shallots",
            "mint",
        ],
    },
    {
        "id": "roti-canai",
        "name": "Roti Canai with Dhal",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/roti-canai/",
        "cuisine": "Malaysian",
        "cook_time": "45 min",
        "difficulty": "Hard",
        "ingredients": [
            "flour",
            "ghee",
            "lentils",
            "onions",
            "tomatoes",
            "garlic",
            "ginger",
            "turmeric",
            "curry powder",
        ],
    },
    {
        "id": "chicken-rendang",
        "name": "Chicken Rendang",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/chicken-rendang/",
        "cuisine": "Malaysian",
        "cook_time": "60 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "coconut milk",
            "lemongrass",
            "galangal",
            "turmeric",
            "dried chillies",
            "shallots",
            "garlic",
            "ginger",
            "kaffir lime leaves",
            "oil",
        ],
    },
    {
        "id": "popiah",
        "name": "Popiah",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/popiah/",
        "cuisine": "Malaysian",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "spring roll wrappers",
            "jicama",
            "carrots",
            "prawns",
            "eggs",
            "bean sprouts",
            "sweet soy sauce",
            "garlic",
            "oil",
        ],
    },
    # ── More Vietnamese ───────────────────────────────────────────────────────
    {
        "id": "com-tam",
        "name": "Com Tam",
        "source": "The Woks of Life",
        "source_url": "https://www.hungryhuy.com/banh-xeo-savory-vietnamese-crepes/",
        "cuisine": "Vietnamese",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "broken rice",
            "pork",
            "fish sauce",
            "garlic",
            "shallots",
            "spring onions",
            "palm sugar",
            "oil",
        ],
    },
    {
        "id": "cha-ca",
        "name": "Cha Ca La Vong",
        "source": "The Woks of Life",
        "source_url": "https://www.cooking-therapy.com/canh-chua/",
        "cuisine": "Vietnamese",
        "cook_time": "30 min",
        "difficulty": "Medium",
        "ingredients": [
            "fish",
            "turmeric",
            "dill",
            "shallots",
            "garlic",
            "fish sauce",
            "rice vermicelli",
            "peanuts",
            "oil",
        ],
    },
    # ── More Thai ─────────────────────────────────────────────────────────────
    {
        "id": "khao-man-gai",
        "name": "Khao Man Gai",
        "source": "The Woks of Life",
        "source_url": "https://vickypham.com/blog/vietnamese-spring-rolls-goi-cuon/",
        "cuisine": "Thai",
        "cook_time": "60 min",
        "difficulty": "Medium",
        "ingredients": [
            "chicken",
            "rice",
            "ginger",
            "garlic",
            "sesame oil",
            "soy sauce",
            "cucumber",
            "spring onions",
            "fermented soy bean",
        ],
    },
    {
        "id": "pad-woon-sen",
        "name": "Pad Woon Sen",
        "source": "The Woks of Life",
        "source_url": "https://www.hungryhuy.com/ca-kho-to-recipe-vietnamese-braised-fish/",
        "cuisine": "Thai",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "glass noodles",
            "eggs",
            "prawns",
            "vegetables",
            "fish sauce",
            "oyster sauce",
            "garlic",
            "spring onions",
            "oil",
        ],
    },
    # ── More Indonesian ───────────────────────────────────────────────────────
    {
        "id": "rawon",
        "name": "Rawon",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/rawon/recipe/",
        "cuisine": "Indonesian",
        "cook_time": "90 min",
        "difficulty": "Hard",
        "ingredients": [
            "beef",
            "black nuts",
            "lemongrass",
            "galangal",
            "shallots",
            "garlic",
            "bean sprouts",
            "spring onions",
            "oil",
        ],
    },
    {
        "id": "pecel",
        "name": "Pecel",
        "source": "Rasa Malaysia",
        "source_url": "https://rasamalaysia.com/pecel/recipe/",
        "cuisine": "Indonesian",
        "cook_time": "20 min",
        "difficulty": "Easy",
        "ingredients": [
            "peanuts",
            "vegetables",
            "tamarind",
            "palm sugar",
            "chillies",
            "garlic",
            "kaffir lime leaves",
            "belacan",
        ],
    },
    # ── More Chinese ──────────────────────────────────────────────────────────
    {
        "id": "char-siu-bao-filling",
        "name": "Char Siu Bao",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/char-siu-bao/",
        "cuisine": "Chinese",
        "cook_time": "60 min",
        "difficulty": "Hard",
        "ingredients": [
            "pork",
            "hoisin sauce",
            "soy sauce",
            "oyster sauce",
            "sesame oil",
            "flour",
            "spring onions",
            "garlic",
        ],
    },
    {
        "id": "spring-rolls",
        "name": "Crispy Spring Rolls",
        "source": "The Woks of Life",
        "source_url": "https://glebekitchen.com/bun-cha-vietnamese-grilled-pork-with-rice-noodles/",
        "cuisine": "Chinese",
        "cook_time": "40 min",
        "difficulty": "Medium",
        "ingredients": [
            "spring roll wrappers",
            "pork",
            "cabbage",
            "carrots",
            "bean sprouts",
            "soy sauce",
            "sesame oil",
            "spring onions",
            "oil",
        ],
    },
    {
        "id": "buddha-delight",
        "name": "Buddha's Delight",
        "source": "The Woks of Life",
        "source_url": "https://thewoksoflife.com/buddhas-delight/",
        "cuisine": "Chinese",
        "cook_time": "30 min",
        "difficulty": "Easy",
        "ingredients": [
            "tofu",
            "glass noodles",
            "mushrooms",
            "bamboo shoots",
            "oyster sauce",
            "sesame oil",
            "soy sauce",
            "garlic",
            "oil",
        ],
    },
]
