"""Canonical pantry ingredient list and type map.

Kept in a standalone module with no Flask dependencies so the pipeline
can import it without triggering the Flask app factory.
"""

PANTRY_ITEMS = [
    "Active dry yeast",
    "Agar agar",
    "All-purpose flour",
    "Annatto",
    "Baby bok choy",
    "Baby corn",
    "Baking powder",
    "Baking soda",
    "Bamboo shoots",
    "Basil leaves",
    "Bay leaves",
    "Bean curd skin",
    "Bean sprouts",
    "Beef",
    "Belacan",
    "Black bean sauce",
    "Black sesame seeds",
    "Black vinegar",
    "Bok choy",
    "Bonito flakes",
    "Bottle gourd",
    "Breadcrumbs",
    "Broccoli",
    "Brown rice",
    "Brown sugar",
    "Butter",
    "Button mushrooms",
    "Cabbage",
    "Candlenut",
    "Capsicum",
    "Cardamom",
    "Carrot",
    "Cashews",
    "Celery",
    "Century egg",
    "Chaat masala",
    "Char siu sauce",
    "Chicken",
    "Chicken bouillon",
    "Chicken breast",
    "Chicken drumstick",
    "Chicken stock",
    "Chicken thigh",
    "Chicken wings",
    "Chickpeas",
    "Chilli",
    "Chilli bean paste",
    "Chilli flakes",
    "Chilli oil",
    "Chinese broccoli",
    "Chinkiang vinegar",
    "Chives",
    "Cilantro",
    "Cinnamon",
    "Coconut cream",
    "Coconut milk",
    "Coconut sugar",
    "Condensed milk",
    "Cooking wine",
    "Cornstarch",
    "Crab",
    "Cucumber",
    "Cumin seeds",
    "Curry leaves",
    "Curry powder",
    "Daikon",
    "Dark soy sauce",
    "Dashi powder",
    "Dashi stock",
    "Desiccated coconut",
    "Doenjang",
    "Doubanjiang",
    "Dried bean curd",
    "Dried chillies",
    "Dried cloud ear fungus",
    "Dried mandarin orange peel",
    "Dried red beans",
    "Dried red dates",
    "Dried scallops",
    "Dried shiitake mushrooms",
    "Dried shrimp",
    "Duck eggs",
    "Dumpling wrappers",
    "Egg noodles",
    "Eggplant",
    "Eggs",
    "Evaporated milk",
    "Fermented bean curd",
    "Fermented black beans",
    "Firm tofu",
    "Fish balls",
    "Fish cakes",
    "Fish fillet",
    "Fish sauce",
    "Five spice powder",
    "Flat rice noodles",
    "Galangal",
    "Galangal powder",
    "Garam masala",
    "Garlic",
    "Ghee",
    "Ginger",
    "Glass noodles",
    "Glutinous rice",
    "Glutinous rice flour",
    "Gochugaru",
    "Gochujang",
    "Goji berry",
    "Gram flour",
    "Grated coconut",
    "Green beans",
    "Green bell pepper",
    "Green chillies",
    "Green curry paste",
    "Ground bean sauce",
    "Hoisin sauce",
    "Honey",
    "Instant noodles",
    "Jasmine rice",
    "Kaffir lime leaves",
    "Kangkung",
    "Kecap manis",
    "Ketchup",
    "Kimchi",
    "King oyster mushroom",
    "Kombu",
    "Laksa paste",
    "Lap cheong",
    "Lard",
    "Lemon",
    "Lemongrass",
    "Lemongrass paste",
    "Lettuce",
    "Light soy sauce",
    "Lily buds",
    "Lime",
    "Maggi seasoning",
    "Mango",
    "Mango powder",
    "Massaman paste",
    "Mayonnaise",
    "Milk",
    "Minced beef",
    "Minced pork",
    "Mirin",
    "Miso paste",
    "MSG",
    "Mung bean",
    "Mushrooms",
    "Mustard",
    "Napa cabbage",
    "Nori",
    "Nutmeg",
    "Olive oil",
    "Onion",
    "Oregano",
    "Oyster sauce",
    "Pad Thai sauce",
    "Palm sugar",
    "Pandan extract",
    "Pandan leaves",
    "Paneer",
    "Panko breadcrumbs",
    "Paprika",
    "Peanut butter",
    "Peanut oil",
    "Peanuts",
    "Plum sauce",
    "Ponzu",
    "Pork belly",
    "Pork butt",
    "Pork chop",
    "Pork ribs",
    "Pork shoulder",
    "Potato",
    "Potato starch",
    "Prawns",
    "Red bell pepper",
    "Red chilli powder",
    "Red curry paste",
    "Red fermented bean curd",
    "Red miso",
    "Red onion",
    "Red vinegar",
    "Rice flour",
    "Rice noodles",
    "Rice vermicelli",
    "Rice vinegar",
    "Rice wine",
    "Rock sugar",
    "Sake",
    "Salmon",
    "Salted egg",
    "Salted fish",
    "Sambal oelek",
    "Sand ginger powder",
    "Seafood mushroom",
    "Sesame oil",
    "Sesame paste",
    "Sesame seeds",
    "Shallots",
    "Shaoxing wine",
    "Shrimp",
    "Shrimp paste",
    "Sichuan peppercorn",
    "Silken tofu",
    "Snow peas",
    "Soba noodles",
    "Soft tofu",
    "Spinach",
    "Spring onions",
    "Spring roll wrappers",
    "Squid",
    "Sriracha",
    "Star anise",
    "Sugar",
    "Sweet chilli sauce",
    "Sweet soy sauce",
    "Tahini",
    "Tamari",
    "Tamarind paste",
    "Tapioca starch",
    "Taucheo",
    "Tempeh",
    "Teriyaki sauce",
    "Thai basil",
    "Tilapia",
    "Toasted coconut",
    "Tofu puffs",
    "Togarashi",
    "Tomato",
    "Tomato puree",
    "Turmeric",
    "Turmeric powder",
    "Udon noodles",
    "Vanilla extract",
    "Vegetable oil",
    "Vegetarian oyster sauce",
    "Wakame",
    "Walnuts",
    "Water chestnuts",
    "White miso",
    "White pepper",
    "White vinegar",
    "Whole wheat flour",
    "Whole wheat noodles",
    "Wonton wrappers",
    "Wood ear mushrooms",
    "XO sauce",
    "Yellow chives",
]
