"""add expired_items_days to user preferences

Revision ID: 024a64ce1ef0
Revises: a427d95ada18
Create Date: 2026-05-01 10:03:18.119233

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "024a64ce1ef0"
down_revision = "a427d95ada18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "expired_items_days", sa.Integer(), nullable=False, server_default="0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("expired_items_days")

    # ### end Alembic commands ###
