"""add view_count to recipe_engagements

Revision ID: 844534649a8f
Revises: d1e2f3a4b5c6
Create Date: 2026-05-01 09:27:57.987571

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "844534649a8f"
down_revision = "d1e2f3a4b5c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_engagements", schema=None) as batch_op:
        batch_op.add_column(sa.Column("view_count", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_engagements", schema=None) as batch_op:
        batch_op.drop_column("view_count")

    # ### end Alembic commands ###
