"""add click_count to recipe_engagements

Revision ID: a427d95ada18
Revises: 844534649a8f
Create Date: 2026-05-01 09:50:28.658950

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a427d95ada18"
down_revision = "844534649a8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_engagements", schema=None) as batch_op:
        batch_op.add_column(sa.Column("click_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_engagements", schema=None) as batch_op:
        batch_op.drop_column("click_count")

    # ### end Alembic commands ###
