"""add recognition cache

Revision ID: cbd9a34f66e5
Revises: ee067008499d
Create Date: 2026-04-19 11:14:30.811550

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbd9a34f66e5"
down_revision = "ee067008499d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recognition_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_hash", sa.String(length=64), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recognition_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recognition_cache_image_hash"), ["image_hash"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recognition_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recognition_cache_image_hash"))

    op.drop_table("recognition_cache")
    # ### end Alembic commands ###
