from datetime import date
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SelectField, SubmitField, HiddenField
from wtforms.fields import DateField
from wtforms.validators import DataRequired, Length, ValidationError

PANTRY_ITEMS = [
    "Active dry yeast",
    "Agar agar",
    "All-purpose flour",
    "Annatto",
    "Baby corn",
    "Baking powder",
    "Baking soda",
    "Bamboo shoots",
    "Bay leaves",
    "Bean curd skin",
    "Belacan",
    "Black bean sauce",
    "Black sesame seeds",
    "Black vinegar",
    "Bonito flakes",
    "Breadcrumbs",
    "Brown rice",
    "Butter",
    "Candlenut",
    "Capsicum",
    "Cardamom",
    "Chaat masala",
    "Char siu sauce",
    "Chicken bouillon",
    "Chilli",
    "Chilli bean paste",
    "Chilli flakes",
    "Chilli oil",
    "Chinkiang vinegar",
    "Cinnamon",
    "Coconut cream",
    "Coconut milk",
    "Coconut sugar",
    "Desiccated coconut",
    "Grated coconut",
    "Toasted coconut",
    "Condensed milk",
    "Cooking wine",
    "Cornstarch",
    "Cumin seeds",
    "Curry leaves",
    "Curry powder",
    "Dark soy sauce",
    "Dashi powder",
    "Dashi stock",
    "Doenjang",
    "Doubanjiang",
    "Dried chillies",
    "Dried mandarin orange peel",
    "Dried red beans",
    "Dried red dates",
    "Dried scallops",
    "Dried shiitake mushrooms",
    "Dried shrimp",
    "Dumpling wrappers",
    "Egg noodles",
    "Eggs",
    "Evaporated milk",
    "Fermented bean curd",
    "Fermented black beans",
    "Firm tofu",
    "Fish balls",
    "Fish cakes",
    "Fish sauce",
    "Five spice powder",
    "Flat rice noodles",
    "Galangal",
    "Galangal powder",
    "Garam masala",
    "Garlic",
    "Ginger",
    "Glass noodles",
    "Glutinous rice",
    "Glutinous rice flour",
    "Gochugaru",
    "Gochujang",
    "Goji berry",
    "Gram flour",
    "Green curry paste",
    "Hoisin sauce",
    "Honey",
    "Instant noodles",
    "Jasmine rice",
    "Kaffir lime leaves",
    "Kecap manis",
    "Ketchup",
    "Kimchi",
    "King oyster mushroom",
    "Kombu",
    "Laksa paste",
    "Lap cheong",
    "Lard",
    "Lemongrass",
    "Lemongrass paste",
    "Light soy sauce",
    "Lily buds",
    "Maggi seasoning",
    "Mango powder",
    "Massaman paste",
    "Mayonnaise",
    "Milk",
    "Mirin",
    "Miso paste",
    "MSG",
    "Mung bean",
    "Nori",
    "Nutmeg",
    "Olive oil",
    "Onion",
    "Oregano",
    "Oyster sauce",
    "Pad Thai sauce",
    "Palm sugar",
    "Pandan extract",
    "Pandan leaves",
    "Paneer",
    "Panko breadcrumbs",
    "Paprika",
    "Peanut butter",
    "Peanut oil",
    "Peanuts",
    "Plum sauce",
    "Ponzu",
    "Potato starch",
    "Red chilli powder",
    "Red curry paste",
    "Red fermented bean curd",
    "Red miso",
    "Red onion",
    "Red vinegar",
    "Rice flour",
    "Rice noodles",
    "Rice vermicelli",
    "Rice vinegar",
    "Rice wine",
    "Rock sugar",
    "Sake",
    "Salted fish",
    "Sambal oelek",
    "Sand ginger powder",
    "Seafood mushroom",
    "Sesame oil",
    "Sesame paste",
    "Sesame seeds",
    "Shallots",
    "Shaoxing wine",
    "Shrimp paste",
    "Sichuan peppercorn",
    "Silken tofu",
    "Soba noodles",
    "Soft tofu",
    "Spring onions",
    "Spring roll wrappers",
    "Sriracha",
    "Star anise",
    "Sugar",
    "Sweet chilli sauce",
    "Sweet soy sauce",
    "Tahini",
    "Tamari",
    "Tamarind paste",
    "Tapioca starch",
    "Taucheo",
    "Tempeh",
    "Teriyaki sauce",
    "Tofu puffs",
    "Togarashi",
    "Tomato puree",
    "Turmeric",
    "Turmeric powder",
    "Udon noodles",
    "Vanilla extract",
    "Vegetable oil",
    "Vegetarian oyster sauce",
    "Wakame",
    "Water chestnuts",
    "White miso",
    "White pepper",
    "White vinegar",
    "Whole wheat flour",
    "Whole wheat noodles",
    "Wonton wrappers",
    "Wood ear mushrooms",
    "XO sauce",
]

INGREDIENT_TYPE_MAP: dict[str, str] = {
    # Sauces
    "Oyster sauce": "sauce",
    "Hoisin sauce": "sauce",
    "Sweet soy sauce": "sauce",
    "Kecap manis": "sauce",
    "XO sauce": "sauce",
    "Black bean sauce": "sauce",
    "Char siu sauce": "sauce",
    "Plum sauce": "sauce",
    "Sweet chilli sauce": "sauce",
    "Teriyaki sauce": "sauce",
    "Pad Thai sauce": "sauce",
    "Green curry paste": "sauce",
    "Massaman paste": "sauce",
    "Red curry paste": "sauce",
    "Sesame paste": "sauce",
    "Tomato puree": "sauce",
    "Vegetarian oyster sauce": "sauce",
    # Oils
    "Sesame oil": "oil",
    "Chilli oil": "oil",
    "Olive oil": "oil",
    "Peanut oil": "oil",
    "Vegetable oil": "oil",
    "Lard": "oil",
    # Condiments
    "Fish sauce": "condiment",
    "Light soy sauce": "condiment",
    "Dark soy sauce": "condiment",
    "Rice vinegar": "condiment",
    "Black vinegar": "condiment",
    "Chinkiang vinegar": "condiment",
    "Mirin": "condiment",
    "Miso paste": "condiment",
    "White miso": "condiment",
    "Red miso": "condiment",
    "Gochujang": "condiment",
    "Doenjang": "condiment",
    "Sambal oelek": "condiment",
    "Sriracha": "condiment",
    "Doubanjiang": "condiment",
    "Chilli bean paste": "condiment",
    "Ponzu": "condiment",
    "Maggi seasoning": "condiment",
    "Shrimp paste": "condiment",
    "Belacan": "condiment",
    "Tamarind paste": "condiment",
    "Laksa paste": "condiment",
    "Dashi powder": "condiment",
    "Dashi stock": "condiment",
    "Lemongrass paste": "condiment",
    "Ketchup": "condiment",
    "Mayonnaise": "condiment",
    "Peanut butter": "condiment",
    "White vinegar": "condiment",
    "Red vinegar": "condiment",
    "Chicken bouillon": "condiment",
    "Fermented bean curd": "condiment",
    "Red fermented bean curd": "condiment",
    "Kimchi": "condiment",
    "Taucheo": "condiment",
    "Tahini": "condiment",
    "Tamari": "condiment",
    "Honey": "condiment",
    "Cooking wine": "condiment",
    # Spices & dried herbs
    "Gochugaru": "spice",
    "Five spice powder": "spice",
    "Curry powder": "spice",
    "Turmeric powder": "spice",
    "White pepper": "spice",
    "Sichuan peppercorn": "spice",
    "Star anise": "spice",
    "Dried chillies": "spice",
    "Chilli flakes": "spice",
    "Togarashi": "spice",
    "Galangal powder": "spice",
    "Garam masala": "spice",
    "Candlenut": "spice",
    "MSG": "spice",
    "Bay leaves": "spice",
    "Cardamom": "spice",
    "Chaat masala": "spice",
    "Cinnamon": "spice",
    "Cumin seeds": "spice",
    "Mango powder": "spice",
    "Oregano": "spice",
    "Paprika": "spice",
    "Red chilli powder": "spice",
    "Sand ginger powder": "spice",
    "Annatto": "spice",
    "Sesame seeds": "spice",
    "Black sesame seeds": "spice",
    # Dried goods
    "Agar agar": "dried",
    "Jasmine rice": "dried",
    "Glutinous rice": "dried",
    "Brown rice": "dried",
    "Rice flour": "dried",
    "Tapioca starch": "dried",
    "Cornstarch": "dried",
    "Potato starch": "dried",
    "Panko breadcrumbs": "dried",
    "Rice noodles": "dried",
    "Glass noodles": "dried",
    "Egg noodles": "dried",
    "Udon noodles": "dried",
    "Soba noodles": "dried",
    "Instant noodles": "dried",
    "Wonton wrappers": "dried",
    "Spring roll wrappers": "dried",
    "Dumpling wrappers": "dried",
    "Dried shiitake mushrooms": "dried",
    "Wood ear mushrooms": "dried",
    "Dried shrimp": "dried",
    "Dried scallops": "dried",
    "Fermented black beans": "dried",
    "Lily buds": "dried",
    "Bean curd skin": "dried",
    "Dried red dates": "dried",
    "Kombu": "dried",
    "Nori": "dried",
    "Wakame": "dried",
    "Bonito flakes": "dried",
    "Lap cheong": "dried",
    "Desiccated coconut": "dried",
    "Grated coconut": "dried",
    "Toasted coconut": "dried",
    "Active dry yeast": "dried",
    "Baking powder": "dried",
    "Baking soda": "dried",
    "Glutinous rice flour": "dried",
    "Gram flour": "dried",
    "All-purpose flour": "dried",
    "Breadcrumbs": "dried",
    "Whole wheat flour": "dried",
    "Whole wheat noodles": "dried",
    "Rice vermicelli": "dried",
    "Flat rice noodles": "dried",
    "Dried mandarin orange peel": "dried",
    "Dried red beans": "dried",
    "Goji berry": "dried",
    "Mung bean": "dried",
    "Peanuts": "dried",
    "Salted fish": "dried",
    # Tofu & soy
    "Silken tofu": "tofu",
    "Firm tofu": "tofu",
    "Tofu puffs": "tofu",
    "Soft tofu": "tofu",
    "Tempeh": "tofu",
    # Seafood
    "Fish balls": "seafood",
    "Fish cakes": "seafood",
    # Dairy
    "Coconut milk": "other",
    "Coconut cream": "other",
    "Condensed milk": "dairy",
    "Evaporated milk": "dairy",
    "Milk": "dairy",
    "Butter": "dairy",
    "Paneer": "dairy",
    # Produce
    "Capsicum": "produce",
    "Chilli": "produce",
    "Galangal": "produce",
    "Garlic": "produce",
    "Ginger": "produce",
    "Lemongrass": "produce",
    "Onion": "produce",
    "Red onion": "produce",
    "Shallots": "produce",
    "Spring onions": "produce",
    "Turmeric": "produce",
    "Water chestnuts": "produce",
    "Bamboo shoots": "produce",
    "Baby corn": "produce",
    "Pandan leaves": "produce",
    "Kaffir lime leaves": "produce",
    "Curry leaves": "produce",
    "King oyster mushroom": "produce",
    "Seafood mushroom": "produce",
    # Other
    "Eggs": "other",
    "Nutmeg": "spice",
    "Sugar": "other",
    "Sake": "other",
    "Shaoxing wine": "other",
    "Coconut sugar": "other",
    "Palm sugar": "other",
    "Rock sugar": "other",
    "Pandan extract": "other",
    "Rice wine": "other",
    "Vanilla extract": "other",
}

LOCATIONS = [
    ("", "Not specified"),
    ("fridge", "Fridge"),
    ("freezer", "Freezer"),
    ("pantry", "Pantry"),
    ("cupboard", "Cupboard"),
    ("counter", "Counter"),
]

ITEM_TYPES = [
    ("unknown", "Unknown"),
    ("sauce", "Sauce"),
    ("oil", "Oil"),
    ("spice", "Spice"),
    ("condiment", "Condiment"),
    ("produce", "Produce"),
    ("dried", "Dried goods"),
    ("tofu", "Tofu"),
    ("seafood", "Seafood"),
    ("dairy", "Dairy"),
    ("other", "Other"),
]


class AddItemForm(FlaskForm):
    name = StringField("Item name", validators=[DataRequired(), Length(min=1, max=256)])
    standard_name = StringField(
        "Standard ingredient name", validators=[Length(max=256)]
    )
    item_type = SelectField("Type", choices=ITEM_TYPES, default="unknown")
    location = StringField("Location", validators=[Length(max=32)])
    expiry_date = DateField("Expiry date", validators=[DataRequired()])
    photo = FileField(
        "Photo (optional)", validators=[FileAllowed(["jpg", "jpeg", "png", "webp"])]
    )
    barcode = StringField("Barcode (optional)", validators=[Length(max=64)])
    photo_paths_json = (
        HiddenField()
    )  # JSON: [{"path": "...", "type": "appearance"}, ...]
    confidence_score = HiddenField()
    cache_hit = HiddenField()
    source = HiddenField()  # "barcode", "photo", or "manual"

    # Product detail fields — passed through hidden fields from barcode lookup
    brands = HiddenField()
    quantity = HiddenField()
    ingredients_text = HiddenField()
    labels_tags = HiddenField()  # JSON list
    product_data_source = HiddenField()  # "off" or "ocr"
    off_nutriscore_grade = HiddenField()
    off_nutriscore_score = HiddenField()
    off_nova_group = HiddenField()
    off_ecoscore_grade = HiddenField()
    off_ecoscore_score = HiddenField()
    off_categories_tags = HiddenField()  # JSON list
    off_allergens_tags = HiddenField()  # JSON list
    off_packaging_tags = HiddenField()  # JSON list
    off_data_quality_tags = HiddenField()  # JSON list

    submit = SubmitField("Save item")

    def validate_expiry_date(self, field):
        today = date.today()
        max_date = today.replace(year=today.year + 5)
        if field.data > max_date:
            raise ValidationError(
                "Expiry date cannot be more than 5 years in the future."
            )
