"""Backfill normalized_ingredients into app/recipes/data.py.

By default only fills in recipes whose normalized_ingredients list is empty,
so manually curated entries are preserved. Pass --force to regenerate all.

Run once (and again whenever PANTRY_ITEMS changes):
    uv run python scripts/normalize_recipe_data.py
    uv run python scripts/normalize_recipe_data.py --force
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

from app.recipes.data import RECIPES
from app.ingredient_normalization import normalize_ingredient
from pipeline.store import emit_data_py


def main() -> None:
    force = "--force" in sys.argv
    enriched = []
    skipped = 0
    for recipe in RECIPES:
        existing = recipe.get("normalized_ingredients", [])
        if existing and not force:
            enriched.append(recipe)
            skipped += 1
            continue
        normalized = [
            normalize_ingredient(i) or i.lower().strip() for i in recipe["ingredients"]
        ]
        enriched.append({**recipe, "normalized_ingredients": normalized})

    output = emit_data_py(enriched, source="scripts/normalize_recipe_data.py")
    # emit_data_py adds a "do not edit by hand" comment suited for generated files,
    # but data.py is manually curated. Replace it with the correct guidance.
    output = output.replace(
        "# Generated by scripts/normalize_recipe_data.py — do not edit by hand.\n",
        "# Run scripts/normalize_recipe_data.py after adding entries to refresh normalized_ingredients.\n",
    )
    out_path = pathlib.Path(__file__).parent.parent / "app" / "recipes" / "data.py"
    out_path.write_text(output)
    print(
        f"Wrote {len(enriched)} recipes to {out_path}"
        + (
            f"  ({skipped} skipped — already had normalized_ingredients; use --force to regenerate)"
            if skipped
            else ""
        )
    )


if __name__ == "__main__":
    main()
